import rateLimit from '@fastify/rate-limit'
import Fastify from 'fastify'
import type { FastifyInstance } from 'fastify'
import rawBody from 'fastify-raw-body'

import { env } from './env.js'
import { devRoutes } from './modules/dev/dev.routes.js'
import { healthRoutes } from './modules/health/health.routes.js'
import { redemptionRoutes } from './modules/redemption/redemption.routes.js'
import { rewardRoutes } from './modules/reward/reward.routes.js'
import { demoRoutes, userRoutes } from './modules/user/user.routes.js'
import { webhookRoutes } from './modules/webhook/webhook.routes.js'
import { applyAuth } from './plugins/auth.js'

export type BuildAppOptions = {
  /**
   * Overrides the global rate limit. Exists so a test can build an app with a
   * limit of two and prove a third request is refused — without which the limit
   * is configuration nobody has ever seen work.
   */
  rateLimit?: { max?: number; timeWindow?: number | string }

  /**
   * Where log lines go. Defaults to stdout.
   *
   * Injectable so a test can read what was actually written and confirm the
   * signature header was censored. Redaction is a security property, and the
   * only way to assert a security property is to observe the output — asserting
   * that the configuration *says* redact is just retyping the configuration.
   */
  loggerDestination?: NodeJS.WritableStream
}

/**
 * Builds the server without starting it.
 *
 * Kept separate from `index.ts` so tests can `app.inject()` requests straight
 * into a real instance — same plugins, same routes, same error handling — with
 * no port to bind and no cleanup race between test files.
 */
export async function buildApp(options: BuildAppOptions = {}): Promise<FastifyInstance> {
  const app = Fastify({
    logger: {
      level: options.loggerDestination ? 'info' : env.LOG_LEVEL,
      ...(options.loggerDestination ? { stream: options.loggerDestination } : {}),

      /**
       * Secrets must never reach a log aggregator, where they are retained far
       * longer and read by far more people than anyone intends.
       *
       * This is what makes logging headers at all defensible — see the request
       * serializer below. Both spellings of the signature header are listed
       * because a partner integration that guesses the other one should still
       * have its attempt censored rather than printed.
       */
      redact: {
        paths: [
          'req.headers["x-webhook-signature"]',
          'req.headers["x-signature"]',
          'req.headers.authorization',
          'req.headers.cookie',
          'req.headers["set-cookie"]',
        ],
        censor: '[redacted]',
      },

      serializers: {
        /**
         * Headers are logged deliberately. Debugging a partner integration
         * almost always comes down to what they actually sent — a missing
         * timestamp, the wrong content type, a signature header under a name we
         * do not read — and none of that is answerable from a log line
         * containing only a method and a path.
         *
         * It is only safe because of the redaction above, so the two belong
         * together: removing one silently makes the other wrong.
         */
        req(request) {
          return {
            method: request.method,
            url: request.url,
            remoteAddress: request.ip,
            headers: request.headers,
          }
        },
      },
    },

    /**
     * Every request carries an id, generated by us.
     *
     * `requestIdHeader: false` refuses to take one from the caller: a partner
     * that reused the same id for every request — or picked one deliberately —
     * would collide their lines with each other, or with someone else's, in the
     * one place we look when something has gone wrong.
     *
     * The webhook route attaches the partner's `event_id` to its own log lines,
     * so a support question that starts with their id can be traced to ours.
     */
    requestIdHeader: false,
    genReqId: () => crypto.randomUUID(),

    /**
     * 32 KB. Every legitimate payload here is a few hundred bytes, and Fastify's
     * 1 MB default is an invitation to make the server buffer megabytes of
     * whatever an unauthenticated caller feels like sending. The cap is checked
     * before the body is read, so an oversized request costs almost nothing.
     */
    bodyLimit: 32 * 1024,
  })

  /**
   * Rate limiting.
   *
   * Registered before the routes so it covers all of them, with the webhook
   * opting into its own, larger allowance below. Two different callers with two
   * different failure modes: a partner catching up after an outage will burst
   * legitimately and must not be throttled into losing events, while the
   * user-facing API is reached from a browser and has no reason to send
   * hundreds of requests a minute.
   *
   * The refusal is a 429 with `Retry-After`, which is a transient signal — a
   * partner should back off and retry, and their event is not lost.
   */
  await app.register(rateLimit, {
    global: true,
    max: options.rateLimit?.max ?? env.RATE_LIMIT_MAX,
    timeWindow: options.rateLimit?.timeWindow ?? '1 minute',

    // In-process counters, which is honest about what this is: one instance's
    // view. Behind more than one instance the effective limit multiplies, and
    // the fix is a shared store (Redis) rather than a bigger number here.

    /**
     * The plugin answers directly rather than throwing, so its response never
     * reaches `setErrorHandler` and this builder is the only place to shape it.
     * Left to itself it sends `error: "Too Many Requests"` — a human sentence
     * where every other endpoint puts a machine code, which is exactly the
     * inconsistency the custom 404 handler exists to prevent.
     *
     * `statusCode` has to be in the returned object because that is what the
     * plugin reads to set the status; without it the reply is a 500. It means
     * this one body carries a field the others do not, which is a smaller price
     * than a client special-casing `error` for a single endpoint.
     */
    errorResponseBuilder: (_request, context) => ({
      statusCode: 429,
      error: 'rate_limited',
      message: `Too many requests. Retry in ${context.after}.`,
    }),
  })

  /**
   * Registered here, before any route, because it works by installing a
   * content-type parser — and a parser can only be installed before the routes
   * that use it are added.
   *
   * The partner signs `${timestamp}.${rawBody}`, so verification needs the
   * exact bytes that were signed. Re-serialising the parsed JSON does not
   * reproduce them: key order and whitespace are not preserved, so the HMAC
   * would fail on payloads that are perfectly valid. By the time a normal
   * handler runs, the raw copy is gone.
   *
   * `global: false` means only routes that opt in with `config: { rawBody: true }`
   * pay the cost of retaining the buffer — in practice, the webhook alone.
   */
  await app.register(rawBody, {
    field: 'rawBody',
    global: false,
    encoding: 'utf8',
    runFirst: true,
  })

  // Applied to the root instance so every route can read request.user. It only
  // resolves an identity and never rejects; routes that require one opt in with
  // requireUser, so the webhook is not forced to invent an acting user it does
  // not have.
  applyAuth(app)

  // Every route lives under /api, health included, so the Vite dev proxy needs
  // exactly one rule and there is no second origin for a browser to refuse.
  await app.register(healthRoutes, { prefix: '/api/health' })
  await app.register(webhookRoutes, { prefix: '/api/webhooks' })
  await app.register(userRoutes, { prefix: '/api' })
  await app.register(demoRoutes, { prefix: '/api/demo' })
  await app.register(rewardRoutes, { prefix: '/api/rewards' })
  await app.register(redemptionRoutes, { prefix: '/api/redemptions' })

  /**
   * Registered only outside production, so these routes do not exist in a real
   * deployment rather than existing behind a flag someone can flip. The
   * simulator signs genuine payloads, so it weakens nothing — but an endpoint
   * that lists every delivery and every balance discrepancy is a development
   * tool, and the safest way to keep it one is for it not to be there.
   */
  if (env.NODE_ENV !== 'production') {
    await app.register(devRoutes, { prefix: '/api/dev' })
  }

  /**
   * Fastify's built-in 404 does not pass through `setErrorHandler`, so without
   * this the API would speak two different error dialects: `{ error, message }`
   * everywhere, and `{ statusCode, error, message }` with a human-readable
   * string in `error` for unknown routes. The web client reads `error` as a
   * machine code, so one envelope for every failure is what keeps that honest.
   */
  app.setNotFoundHandler((request, reply) =>
    reply.status(404).send({
      error: 'not_found',
      message: `Route ${request.method}:${request.url} not found.`,
    }),
  )

  /**
   * A single error shape for anything that escapes a handler.
   *
   * Internal errors are logged in full and answered with a generic message: an
   * endpoint that moves points should not narrate its stack trace, constraint
   * names or table structure to an untrusted caller. Client errors (4xx) carry
   * their message through, because those are the ones the caller can act on.
   */
  app.setErrorHandler((error: unknown, request, reply) => {
    // Fastify types this as `unknown` because JavaScript permits throwing any
    // value, not just an Error. Reading `.statusCode` off it directly would be
    // a lie that happens to work until something throws a string.
    const details = error as { statusCode?: number; code?: string; message?: string }
    const status = typeof details.statusCode === 'number' ? details.statusCode : 500

    if (status >= 500) {
      request.log.error({ err: error }, 'unhandled error')
      return reply.status(status).send({
        error: 'internal_error',
        message: 'The request could not be completed.',
      })
    }


    request.log.warn({ err: error }, 'request rejected')
    return reply.status(status).send({
      error: details.code ?? 'bad_request',
      message: details.message ?? 'The request was rejected.',
    })
  })

  return app
}
